#Requires -Version 5.1
<#
    tcp_counter_rate.ps1 - how often the TCP performance-counter read fails, per condition (backlog #38).

    This is a measurement, not a test, and it is run on demand: it is deliberately not part of
    tests\Invoke-ValidationChain.ps1. Whether the read fails at all is a property of a machine under load, and a step
    that fails one run in twenty teaches nothing while eroding trust in every other step - this project already owns
    one such case and recorded it as a measurement rather than hiding it behind a re-run (backlog #25). What keeps the
    #38 fix fixed are the deterministic unit cases in tests\unit_tests.ps1; what this script is for is the rate those
    cases cannot reach: whether the failure happens on a given machine, how often, and whether the retry moves it.

    What it measures. Each iteration takes one snapshot through the shipped Get-TcpCounterSnapshot, which reads TCPv4
    and TCPv6 in turn and gives each read up to two attempts. Per condition it reports, over 2 x Iterations reads:

      first-attempt failures  - reads that failed once. Before 1.2.8 every one of these lost its measurement; with the
                                retry they lose it only if the second attempt fails too. This is the rate the fix
                                moves, and the number to compare between conditions.
      lost reads              - reads where both attempts failed, which still write "Unable to Check".
      seconds                 - what the reads cost, since a failed attempt spends its eight-second limit.

    The conditions. "idle" is the machine as it is. "load" is deliberate local file I/O generated by this script -
    a tree it writes itself and then copies, repeatedly, in background jobs - because Win32_PerfRawData_* queries are
    sensitive to disk and CPU load and because a sync client cannot be assumed (CI has none). The walk's own condition
    on 2026-09-08 was narrower than either: the first run inside a copy extracted moments earlier, where a sync client
    or an antivirus scan is reading thirty-one new files. This script does not reproduce that; it produces the load
    both explanations share, on any machine, without a cloud folder.

    Usage:
      tests\tcp_counter_rate.ps1                                  20 iterations idle, then 20 under load
      tests\tcp_counter_rate.ps1 -Iterations 50 -Jobs 4           more of both
      tests\tcp_counter_rate.ps1 -Conditions idle                 one condition only
      tests\tcp_counter_rate.ps1 -ScriptPath <path to a package>  measure a different copy of the tool

    It exits 0 whenever it completed, whatever the rates were: a rate is a reading, and this script never decides
    that a machine has passed or failed.
#>
[CmdletBinding()]
param(
    [string]$ScriptPath = "",
    [int]$Iterations = 20,
    [ValidateSet('idle', 'load', 'both')][string]$Conditions = 'both',
    [int]$Jobs = 2,
    [int]$LoadFileCount = 400,
    [int]$LoadFileKb = 256,
    [string]$WorkDir = (Join-Path $env:TEMP ('nhc-counter-rate-' + [guid]::NewGuid().ToString('N').Substring(0, 8)))
)

$ErrorActionPreference = 'Stop'

# $PSScriptRoot is empty while the parameter defaults are being bound, so the package this repository ships is
# resolved here instead of in the param block.
if ([string]::IsNullOrWhiteSpace($ScriptPath)) {
    $ScriptPath = Join-Path (Split-Path -Parent $PSScriptRoot) 'healthcheck\en-US\NetworkHealthCheck.ps1'
}
if ($Iterations -lt 1) { throw 'Iterations must be at least 1.' }
if (-not (Test-Path -LiteralPath $ScriptPath)) { throw "Script not found: $ScriptPath" }

# The functions under measurement are the shipped ones, read off the AST of the package being measured, so that this
# script cannot drift from what the tool does. Nothing of the script's main body runs.
$tokens = $null; $errors = $null
$ast = [System.Management.Automation.Language.Parser]::ParseFile((Resolve-Path -LiteralPath $ScriptPath).Path, [ref]$tokens, [ref]$errors)
$wanted = 'Get-CimOrWmiInstance', 'Get-TcpCounterSnapshot', 'Get-ExceptionDetails', 'Get-ExceptionDiagnostics', 'ConvertTo-UInt64Safe', 'Get-NetworkErrorCauseText', 'Add-NetworkErrorCause', 'Test-IsNumericValue'
$funcs = $ast.FindAll({ param($n) $n -is [System.Management.Automation.Language.FunctionDefinitionAst] -and $wanted -contains $n.Name }, $true)
foreach ($f in $funcs) { Invoke-Expression $f.Extent.Text }
$loaded = @($funcs | ForEach-Object { $_.Name })
$missing = @($wanted | Where-Object { $loaded -notcontains $_ })
if ($missing.Count -gt 0) { throw ("These functions are not in {0}: {1}" -f $ScriptPath, ($missing -join ', ')) }

function Start-LoadJobs {
    param([string]$Root, [int]$Count, [int]$FileKb, [int]$JobCount)

    # A tree written here and then copied over and over: the load is this script's own, so the reading is repeatable
    # on a machine with no sync client and no antivirus exclusion to arrange.
    $source = Join-Path $Root 'tree'
    New-Item -ItemType Directory -Force -Path $source | Out-Null
    $block = [byte[]]::new($FileKb * 1024)
    (New-Object System.Random 20260908).NextBytes($block)
    for ($i = 0; $i -lt $Count; $i++) {
        [System.IO.File]::WriteAllBytes((Join-Path $source ("load_{0:d4}.bin" -f $i)), $block)
    }
    $jobs = @()
    for ($j = 1; $j -le $JobCount; $j++) {
        $target = Join-Path $Root ("copy_$j")
        $jobs += Start-Job -ScriptBlock {
            param($from, $to)
            while ($true) {
                Copy-Item -LiteralPath $from -Destination $to -Recurse -Force -ErrorAction SilentlyContinue
                Remove-Item -LiteralPath $to -Recurse -Force -ErrorAction SilentlyContinue
            }
        } -ArgumentList $source, $target
    }
    return $jobs
}

function Measure-Condition {
    param([string]$Name, [int]$Count)

    $reads = New-Object System.Collections.ArrayList
    for ($i = 1; $i -le $Count; $i++) {
        $started = Get-Date
        $snapshot = Get-TcpCounterSnapshot
        $elapsed = [math]::Round(((Get-Date) - $started).TotalSeconds, 2)
        foreach ($protocol in @('TCPv4', 'TCPv6')) {
            $failed = @(@($snapshot.FailedAttempts) | Where-Object { [string]$_.Protocol -eq $protocol })
            [void]$reads.Add([pscustomobject]@{
                Condition   = $Name
                Iteration   = $i
                Protocol    = $protocol
                Read        = $snapshot.Counters.ContainsKey($protocol)
                Attempts    = 1 + $failed.Count
                FailedFirst = ($failed.Count -gt 0)
                FailSeconds = [math]::Round((($failed | Measure-Object -Property Seconds -Sum).Sum), 1)
                Error       = (@($snapshot.Errors | Where-Object { [string]$_.Protocol -eq $protocol } | ForEach-Object { ($_.Error -split "`r`n")[0] }) -join ' | ')
            })
        }
        Write-Progress -Activity ("Reading TCP counters ({0})" -f $Name) -Status ("iteration $i of $Count, $elapsed s") -PercentComplete ([int](100 * $i / $Count))
    }
    Write-Progress -Activity ("Reading TCP counters ({0})" -f $Name) -Completed
    return @($reads)
}

function Write-ConditionSummary {
    param([string]$Name, [object[]]$Reads)

    $total = @($Reads).Count
    $firstFailures = @($Reads | Where-Object { $_.FailedFirst })
    $lost = @($Reads | Where-Object { -not $_.Read })
    $seconds = [math]::Round((($Reads | Measure-Object -Property FailSeconds -Sum).Sum), 1)
    $rate = 0.0
    if ($total -gt 0) { $rate = [math]::Round((100.0 * $firstFailures.Count / $total), 1) }
    $lostRate = 0.0
    if ($total -gt 0) { $lostRate = [math]::Round((100.0 * $lost.Count / $total), 1) }
    Write-Output ("{0,-6} {1,6} reads   first-attempt failures {2,4} ({3,5}%)   lost after both attempts {4,4} ({5,5}%)   {6} s spent on failed attempts" -f $Name, $total, $firstFailures.Count, $rate, $lost.Count, $lostRate, $seconds)
    foreach ($item in $firstFailures) {
        Write-Output ("       iteration {0,3} {1}: attempt 1 failed after {2} s{3}" -f $item.Iteration, $item.Protocol, $item.FailSeconds, $(if ($item.Read) { ', the second attempt succeeded' } else { ', and so did the second: ' + $item.Error }))
    }
}

Write-Output ("Machine: {0}   PowerShell {1}   {2}" -f $env:COMPUTERNAME, $PSVersionTable.PSVersion, (Get-Date -Format 'yyyy-MM-dd HH:mm:ss'))
Write-Output ("Package: {0}" -f (Resolve-Path -LiteralPath $ScriptPath).Path)
Write-Output ("Plan: {0} iteration(s) per condition, two reads each, up to two attempts per read" -f $Iterations)
Write-Output ""

$results = @{}
if ($Conditions -eq 'idle' -or $Conditions -eq 'both') {
    $results['idle'] = Measure-Condition -Name 'idle' -Count $Iterations
}
if ($Conditions -eq 'load' -or $Conditions -eq 'both') {
    New-Item -ItemType Directory -Force -Path $WorkDir | Out-Null
    $loadJobs = @()
    try {
        Write-Output ("Writing {0} x {1} KB into {2} and copying it in {3} background job(s)..." -f $LoadFileCount, $LoadFileKb, $WorkDir, $Jobs)
        $loadJobs = Start-LoadJobs -Root $WorkDir -Count $LoadFileCount -FileKb $LoadFileKb -JobCount $Jobs
        $results['load'] = Measure-Condition -Name 'load' -Count $Iterations
    }
    finally {
        foreach ($job in $loadJobs) {
            Stop-Job -Job $job -ErrorAction SilentlyContinue
            Remove-Job -Job $job -Force -ErrorAction SilentlyContinue
        }
        Remove-Item -LiteralPath $WorkDir -Recurse -Force -ErrorAction SilentlyContinue
    }
}

Write-Output ""
foreach ($name in @('idle', 'load')) {
    if ($results.ContainsKey($name)) { Write-ConditionSummary -Name $name -Reads $results[$name] }
}
Write-Output ""
Write-Output "A reading, not a verdict: this script never decides that a machine passed or failed, and one campaign on"
Write-Output "one machine settles nothing on its own. What a campaign can show is whether the first-attempt failure"
Write-Output "rate differs between the conditions, and how many of those failures the second attempt recovered."
exit 0
